[package]
name = "learn_jvm"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
zip = "0.6.6"
walkdir = "2.3.3"
thiserror = "1"
byteorder = "1"
